### ISSUE TITLE
execvp error on Debian Stretch

### ISSUE THREAD

**Issue by RMCampos** [marcosps/nsexec#3]
Hi there! I'm trying to run on latest stable Debian version today (2018, January) (Strech 9.3).

Build: success
Execute: fail
Message error: execvp: No such file or directory

`$ nsexec --unshare-all`
execvp: No such file or directory

More info
`$ ip link`
3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether 52:54:00:17:07:7d brd ff:ff:ff:ff:ff:ff
4: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast master virbr0 state DOWN mode DEFAULT group default qlen 1000
    link/ether 52:54:00:17:07:7d brd ff:ff:ff:ff:ff:ff

`# virsh net-info default`
Name:           default
UUID:           063089c4-7cf5-4a6a-aa48-1233a06b05e4
Active:         yes
Persistent:     yes
Autostart:      no
Bridge:         virbr0

`$ echo $PATH`
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/jdk1.7.0_80/bin:/home/ricardo/erpWeb/apache-maven-3.3.3/bin

`$ which bash`
/bin/bash

**Comment by marcosps** [comment]
Issue solved by commit marcosps@3ebca4efb154f6d1050122361530f0ae12a70e8e
